---
title: "Budžeti gradova Srbije"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: https://git.io/Jfwiu
runtime: shiny
---

```{r global, include=FALSE}
library(readr)
library(shiny)
library(plotly)
library(tidyverse)
library(flexdashboard)
library(DT)
prihodi <- read_csv("data/prihodi.csv")
rashodi <- read_csv("data/rashodi.csv")
prihodi <- prihodi %>% mutate(ukupno = budzet + sopstveni_izvori + ostali_izvori)
rashodi <- rashodi %>% mutate(ukupno = budzet + sopstveni_izvori + ostali_izvori)

source("functions.R")
```

Sidebar {.sidebar}
======================================================================
```{r}
selectInput("grad", "Izaberite grad", unique(prihodi$grad))
```

Dashboard
======================================================================



Row 
-----------------------------------------------------------------------
### Prvih 5 grupa po prihodu {data-padding=10}
```{r}
renderPlotly({
  df <- prepare_data_for_barplot(prihodi, input$grad)
  
  plot <- plot_top_earning_or_spending(df, "Prvih 5 funkcija po prihodu", "Funkcija", "Prihod", "green")
  ggplotly(plot)
})
```

### Prvih 5 grupa po rashodu {data-padding=10}
```{r}
renderPlotly({
  df <- rashodi
  df$ukupno <- df$ukupno * -1
  df <- prepare_data_for_barplot(df, input$grad)
  
  plot <- plot_top_earning_or_spending(df, "Prvih 5 funkcija po rashodu", "Funkcija", "Rashod", "red")
  ggplotly(plot)
        
})
```

Row
-----------------------------------------------------------------------

### Struktura prihoda po stavkama {data-padding=10}
```{r}
renderPlotly({
  plot_treemap(prihodi, input$grad)
})
```

### Struktura rashoda po stavkama {data-padding=10}
```{r}
renderPlotly({
  df <- rashodi
  df$ukupno <- df$ukupno * -1
  plot_treemap(df, input$grad)
})
```

Tabela
======================================================================
Row
-----------------------------------------------------------------------
### Prihodi {.value-box}

```{r}

renderValueBox({
  df <- prihodi %>% filter(grad == input$grad)
  ukupni_prihodi <- sum(df$ukupno)
  valueBox(ukupni_prihodi, icon = "fas fa-money-bill-wave")
})
```

### Rashodi {.value-box}

```{r}

renderValueBox({
  df <- rashodi %>% filter(grad == input$grad)
  ukupni_rashodi <- sum(df$ukupno) * -1
  valueBox(ukupni_rashodi, icon = "fas fa-money-bill-wave")
})
```


### Dohodak {.value-box}

```{r}
renderValueBox({
  pr <- prihodi %>% filter(grad == input$grad)
  ra <- rashodi %>% filter(grad == input$grad)
  dohodak <- sum(pr$ukupno) + sum(ra$ukupno)
  
  valueBox(dohodak, icon = "fas fa-money-bill-wave")
})
```

Row {.tabset}
-----------------------------------------------------------------------

### Prihodi
```{r}
renderTable({
  df <- prihodi %>% filter(grad == input$grad)
  df %>% select(-c(grad, X1))
})
```

### Rashodi
```{r}
renderTable({
  df <- rashodi %>% filter(grad == input$grad)
  df %>% select(-c(grad, X1))})
```
