---
title: "Budžeti gradova Srbije"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: https://git.io/Jfwiu
runtime: shiny
---

```{r global, include=FALSE}
library(readr)
library(shiny)
library(plotly)
library(tidyverse)
library(flexdashboard)
library(DT)
prihodi <- read_csv("data/prihodi.csv")
rashodi <- read_csv("data/rashodi.csv")
prihodi <- prihodi %>% mutate(ukupno = budzet + sopstveni_izvori + ostali_izvori)
rashodi <- rashodi %>% mutate(ukupno = budzet + sopstveni_izvori + ostali_izvori)
```

Sidebar {.sidebar}
======================================================================
```{r}
selectInput("grad", "Izaberite grad", unique(prihodi$grad))
```

Dashboard
======================================================================



Row 
-----------------------------------------------------------------------
### Prvih 5 stavki po prihodu {data-padding=10}
```{r}
renderPlotly({
        
        df <- prihodi %>% filter(grad == input$grad) %>%
            group_by(grupa)
        df <- summarise(df, budzet = sum(ukupno))
        df <- df %>% arrange(desc(budzet))
        df <- df[1:5,] # In case there are multiple rows with the same budget
        
        df$grupa <- factor(df$grupa, levels = df$grupa[order(df$budzet)])
        plot <- df %>% ggplot(aes(x=grupa, y=budzet)) +
            geom_col(fill = "green", color="black") +
            theme(text = element_text(size=12)) +
            scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) +
            ggtitle("Prvih 5 stavki po prihodu") +
            xlab("Stavka") +
            ylab("Prihod u RSD") +
            theme_minimal()
        
        ggplotly(plot)

    })
```

### Prvih 5 stavki po rashodu {data-padding=10}
```{r}
renderPlotly({
        
        df <- rashodi %>% filter(grad == input$grad) %>%
                group_by(funkcija)
        df <- summarise(df, budzet = sum(ukupno))
        df$budzet <- df$budzet * -1
        df <- df %>% arrange(desc(budzet))
        df <- df[1:5,] # In case there are multiple rows with the same budget
        
        
        df$funkcija <- factor(df$funkcija, levels = df$funkcija[order(df$budzet)])
        plot <- df %>% ggplot(aes(x=funkcija, y=budzet)) +
            geom_col(fill= "red", color="black") +
            theme(text = element_text(size=12)) +
            scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) +
            ggtitle("Prvih 5 stavki po rashodu") +
            xlab("Stavka") +
            ylab("Rashod u RSD") +
            theme_minimal()
        
        ggplotly(plot)
        
    })
```

Row
-----------------------------------------------------------------------

### Struktura prihoda po stavkama {data-padding=10}
```{r}
renderPlotly({
  df <- prihodi %>% filter(grad == input$grad)
  
  # Several grupa's can have the same ekonomska_klasa inside them so we need a group by both of these variables to make them unique
  # We will take the sum of the groups (tibble groups) as their budgets since the functions of their entries are similar enough
  df <- df %>% group_by(ekonomska_klasa, grupa)
  df <- df %>% summarise(ukupno = sum(ukupno))
  df <- as.data.frame(df) %>% mutate(ekonomska_klasa = paste(ekonomska_klasa, "-", grupa))
  
  df_by_grupa <- prihodi %>% filter(grad == input$grad) %>%
    group_by(grupa)
  df_by_grupa <- df_by_grupa %>% summarise(budzet = sum(ukupno))
  
  plot_ly(
    type='treemap',
    branchvalues="total",
    labels=c(df_by_grupa$grupa, df$ekonomska_klasa),
    parents=c(rep(NA, length(df_by_grupa$grupa)), df$grupa),
    values= c(df_by_grupa$budzet, df$ukupno))
})
```

### Struktura rashoda po stavkama {data-padding=10}
```{r}
renderPlotly({
        
  df <- rashodi %>% filter(grad == input$grad)
  df$ukupno <- df$ukupno * -1
  
  # Several funkcija's can have the same ekonomska_klasifikacija inside them so we need a group by both of these variables to make them unique
  # We will take the sum of the groups (tibble groups) as their budgets since the functions of their entries are similar enough
  df <- df %>% group_by(ekonomska_klasifikacija, funkcija)
  df <- df %>% summarise(ukupno = sum(ukupno))
  df <- as.data.frame(df) %>%  mutate(ekonomska_klasifikacija = paste(ekonomska_klasifikacija, "-", funkcija))
  
  df_by_grupa <- rashodi %>% filter(grad == input$grad) %>%
    group_by(funkcija)
  df_by_grupa <- df_by_grupa %>% summarise(budzet = sum(ukupno) * -1)
  
  plot_ly(
    type='treemap',
    branchvalues="total",
    labels=c(df_by_grupa$funkcija, df$ekonomska_klasifikacija),
    parents=c(rep(NA, length(df_by_grupa$funkcija)), df$funkcija),
    values= c(df_by_grupa$budzet, df$ukupno))
        
})
```

Tabela
======================================================================
Row
-----------------------------------------------------------------------
### Prihodi {.value-box}

```{r}

renderValueBox({
  df <- prihodi %>% filter(grad == input$grad)
  ukupni_prihodi <- sum(df$ukupno)
  valueBox(ukupni_prihodi, icon = "fas fa-money-bill-wave")
})
```

### Rashodi {.value-box}

```{r}

renderValueBox({
  df <- rashodi %>% filter(grad == input$grad)
  ukupni_rashodi <- sum(df$ukupno) * -1
  valueBox(ukupni_rashodi, icon = "fas fa-money-bill-wave")
})
```


### Dohodak {.value-box}

```{r}
renderValueBox({
  pr <- prihodi %>% filter(grad == input$grad)
  ra <- rashodi %>% filter(grad == input$grad)
  dohodak <- sum(pr$ukupno) + sum(ra$ukupno)
  
  valueBox(dohodak, icon = "fas fa-money-bill-wave")
})
```

Row {.tabset}
-----------------------------------------------------------------------

### Prihodi
```{r}
renderTable({
  df <- prihodi %>% filter(grad == input$grad)
  df %>% select(-c(grad, X1))
})
```

### Rashodi
```{r}
renderTable({
  df <- rashodi %>% filter(grad == input$grad)
  df %>% select(-c(grad, X1))})
```
